pub fn map_to_file_ext(mimetype: &String) -> &'static str {
    match mimetype.as_str() {
        "application/mbox" => "mbox",
        "application/pdf" => "pdf",
        "application/pgp-signature" => "asc",
        "application/x-7z-compressed" => "7z",
        "application/x-bzip" => "bz",
        "application/x-bzip2" => "bz2",
        "application/x-gzip" => "gz",
        "application/x-rar-compressed" => "rar",
        "application/x-tar" => "tar",
        "application/x-xz" => "xz",
        "application/zip" => "zip",
        "audio/mpeg" => "mp3",
        "audio/ogg" => "ogg",
        "audio/wav" => "wav",
        "audio/webm" => "webm",
        "image/bmp" => "bmp",
        "image/gif" => "gif",
        "image/jpeg" => "jpg",
        "image/png" => "png",
        "image/svg+xml" => "svg",
        "image/tiff" => "tiff",
        "image/webp" => "webp",
        "message/rfc822" => "eml",
        "text/html" => "html",
        "text/plain" => "txt",
        "video/mp4" => "mp4",
        "video/ogg" => "ogg",
        "video/webm" => "webm",
        _ => "dat",
    }
}
