[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "~1.0", features = ["backtrace"] }
async-stream = "0.3"
bytes = "1.5"
rand = "0.8"
tokio = { version = "1.32", features = ["full"] }
tokio-stream = { version = "0.1", features = ["io-util"] }
