[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "~4.4.0", features = ["derive"] }
rusty-processing = { version = "0.1.0", path = "../rusty-processing" }
anyhow = "1.0.75"
